### ISSUE TITLE
Medidor de glucosa continuo - Describir en estas implementaciones los sistemas de medición, actuación y visualización si correspondiera, según el esquema de dispositivos.

### ISSUE THREAD

**Issue by FedeBirge** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-1er-semana-grupo-4#12]

**Comment by Emygut** [comment]
4. Medidor de glucosa continuo - Describir en estas implementaciones los sistemas de medición, actuación y visualización si correspondiera, según el esquema de dispositivos. # asignada
